// @ts-nocheck
import type {
  AddressBooks,
  VCard,
} from '@/features/address_books/address-books-types'
import type { CalendarsResponse } from '@/features/calendars/calendars-types'

/**
 * Default data for calendars
 * Used when a user visits the app for the first time
 */
export const DEFAULT_CALENDARS: CalendarsResponse = {
  personal: [
    {
      id: 'personal-cal-1',
      name: 'Personal',
      description: 'My personal calendar',
      color: '#3b82f6',
      type: 'personal',
      default: true,
      read_only: false,
      owner: 'user@example.com',
      event_duration: 30,
      show_as_busy: true,
      event_notifications: [
        { method: 'popup', minutes_before: 0 },
        { method: 'email', minutes_before: 15 },
      ],
      all_day_notifications: [{ method: 'popup', minutes_before: 1440 }],
      created_at: '2024-01-01T00:00:00.000Z',
      updated_at: '2024-01-01T00:00:00.000Z',
    },
    {
      id: 'personal-cal-2',
      name: 'Birthdays',
      description: 'Birthdays and anniversaries',
      color: '#ec4899',
      type: 'personal',
      default: false,
      read_only: false,
      owner: 'user@example.com',
      event_duration: 0,
      show_as_busy: false,
      event_notifications: [{ method: 'popup', minutes_before: 0 }],
      all_day_notifications: [{ method: 'popup', minutes_before: 1440 }],
      created_at: '2024-01-01T00:00:00.000Z',
      updated_at: '2024-01-01T00:00:00.000Z',
    },
  ],
  shared: [
    {
      id: 'shared-cal-1',
      name: 'Team Calendar',
      description: 'Shared team events and meetings',
      color: '#10b981',
      type: 'shared',
      default: false,
      read_only: false,
      owner: 'team-lead@example.com',
      permissions: 'readwrite',
      event_duration: 60,
      show_as_busy: true,
      event_notifications: [
        { method: 'popup', minutes_before: 0 },
        { method: 'email', minutes_before: 30 },
      ],
      all_day_notifications: [{ method: 'popup', minutes_before: 1440 }],
      created_at: '2024-01-01T00:00:00.000Z',
      updated_at: '2024-01-01T00:00:00.000Z',
    },
    {
      id: 'shared-cal-2',
      name: 'Company Meetings',
      description: 'All-hands meetings and announcements',
      color: '#8b5cf6',
      type: 'shared',
      default: false,
      read_only: true,
      owner: 'admin@example.com',
      permissions: 'read',
      event_duration: 60,
      show_as_busy: true,
      event_notifications: [{ method: 'popup', minutes_before: 0 }],
      all_day_notifications: [{ method: 'popup', minutes_before: 1440 }],
      created_at: '2024-01-01T00:00:00.000Z',
      updated_at: '2024-01-01T00:00:00.000Z',
    },
  ],
  subscriptions: [
    {
      id: 'sub-cal-1',
      name: 'Weather Calendar',
      description: 'Weather events subscription',
      color: '#06b6d4',
      type: 'subscription',
      default: false,
      read_only: true,
      owner: 'weather-service@example.com',
      url: 'https://weather-service.com/calendar',
      event_notifications: [],
      all_day_notifications: [],
      created_at: '2024-01-01T00:00:00.000Z',
      updated_at: '2024-01-01T00:00:00.000Z',
    },
  ],
}

/**
 * Default data for address books
 * Used when a user visits the app for the first time
 */
export const DEFAULT_ADDRESS_BOOKS: AddressBooks = {
  globals: [
    {
      name: 'Global',
      description: 'Global address book',
      type: 'global',
      id: 'global',
      created_at: '2024-01-01T00:00:00.000Z',
      updated_at: '2024-01-01T00:00:00.000Z',
    },
    {
      name: 'Customers',
      description: 'Customers address book',
      type: 'global',
      id: 'customers',
      created_at: '2024-01-01T00:00:00.000Z',
      updated_at: '2024-01-01T00:00:00.000Z',
    },
  ],
  personals: [
    {
      name: 'Work',
      description: 'Work address book',
      type: 'personal',
      id: 'work',
      default: true,
      created_at: '2024-01-01T00:00:00.000Z',
      updated_at: '2024-01-01T00:00:00.000Z',
    },
    {
      name: 'Personal',
      description: 'Personal contacts',
      type: 'personal',
      id: 'personal',
      created_at: '2024-01-01T00:00:00.000Z',
      updated_at: '2024-01-01T00:00:00.000Z',
    },
  ],
  subscriptions: [
    {
      name: 'Contacts',
      description: 'A quirky, shared demo address book for otter enthusiasts.',
      type: 'shared',
      id: 'contacts',
      created_at: '2024-02-29T12:34:56.000Z',
      updated_at: '2024-02-29T12:34:56.000Z',
    },
  ],
}

/**
 * Default data for contacts (VCards)
 * Used when a user visits the app for the first time
 * Structure: Key = book_id, Value = array of VCards
 */
export const DEFAULT_VCARDS: Record<string, VCard[]> = {
  work: [
    {
      id: '1',
      version: '4.0',
      firstName: 'John',
      lastName: 'Doe',
      middleName: 'A.',
      prefix: 'Mr.',
      suffix: 'Jr.',
      nickname: 'Johnny',
      title: 'Software Engineer',
      organization: 'Tech Corp',
      department: 'Development',
      jobTitle: 'Frontend Developer',
      note: 'A sample VCard entry',
      categories: ['friend', 'colleague'],
      urls: ['https://example.com'],
      photos: ['https://example.com/photo.jpg'],
      emails: ['john.doe@example.com'],
      phoneNumbers: ['+1234567890'],
      addresses: ['123 Main St, Anytown, USA'],
      impp: ['sip:john.doe@example.com'],
      geo: '37.7749,-122.4194',
      birthday: '1990-01-01',
      anniversary: '2020-01-01',
      sound: 'https://example.com/sound.mp3',
      uid: '12345',
      key: 'public-key',
      created_at: '2024-01-01T00:00:00.000Z',
      updated_at: '2024-01-01T00:00:00.000Z',
    },
    {
      id: '2',
      version: '4.0',
      firstName: 'Jane',
      lastName: 'Smith',
      middleName: 'B.',
      prefix: 'Ms.',
      suffix: '',
      nickname: 'Janey',
      title: 'Project Manager',
      organization: 'Tech Corp',
      department: 'Management',
      jobTitle: 'Team Lead',
      note: 'Another sample VCard entry',
      categories: ['manager', 'colleague'],
      urls: ['https://example.org'],
      photos: ['https://example.org/photo.jpg'],
      emails: ['jane.smith@example.org'],
      phoneNumbers: ['+9876543210'],
      addresses: ['456 Elm St, Othertown, USA'],
      impp: ['sip:jane.smith@example.org'],
      geo: '40.7128,-74.0060',
      birthday: '1985-05-15',
      anniversary: '2015-06-15',
      sound: 'https://example.org/sound.mp3',
      uid: '67890',
      key: 'public-key-2',
      created_at: '2024-01-01T00:00:00.000Z',
      updated_at: '2024-01-01T00:00:00.000Z',
    },
    {
      id: '3',
      version: '4.0',
      firstName: 'Brian',
      lastName: 'Topgoush',
      middleName: 'C.',
      prefix: 'Mr.',
      suffix: '',
      nickname: 'Bri',
      title: 'Designer',
      organization: 'Creative Studio',
      department: 'Design',
      jobTitle: 'UI/UX Designer',
      note: 'Creative professional',
      categories: ['designer', 'colleague'],
      urls: ['https://briantopgoush.design'],
      photos: ['https://example.com/brian.jpg'],
      emails: ['brian.topgoush@example.com'],
      phoneNumbers: ['+1122334455'],
      addresses: ['789 Design Ave, Creativetown, USA'],
      impp: ['sip:brian.topgoush@example.com'],
      geo: '34.0522,-118.2437',
      birthday: '1992-03-20',
      anniversary: '2018-09-10',
      sound: 'https://example.com/brian-sound.mp3',
      uid: '33333',
      key: 'public-key-3',
      created_at: '2024-01-01T00:00:00.000Z',
      updated_at: '2024-01-01T00:00:00.000Z',
    },
    {
      id: 'list-sales-team',
      version: '4.0',
      kind: 'group',
      firstName: 'Sales Team',
      lastName: '',
      note: 'Internal sales distribution list',
      members: [
        {
          contactId: '1',
          email: 'john.doe@example.com',
          displayName: 'John Doe',
        },
        {
          contactId: '2',
          email: 'jane.smith@example.org',
          displayName: 'Jane Smith',
        },
      ],
      categories: [],
      urls: [],
      photos: [],
      emails: [],
      phoneNumbers: [],
      addresses: [],
      impp: [],
      created_at: '2024-01-01T00:00:00.000Z',
      updated_at: '2024-01-01T00:00:00.000Z',
    },
  ],
  personal: [],
  global: [
    {
      id: '4',
      version: '4.0',
      firstName: 'Jocelyne',
      lastName: 'Shroud',
      middleName: 'D.',
      prefix: 'Ms.',
      suffix: '',
      nickname: 'Joss',
      title: 'Marketing Director',
      organization: 'Marketing Pro',
      department: 'Marketing',
      jobTitle: 'Marketing Director',
      note: 'Marketing expert',
      categories: ['marketing', 'manager'],
      urls: ['https://jocelyneshroud.marketing'],
      photos: ['https://example.com/jocelyne.jpg'],
      emails: ['jocelyne.shroud@example.com'],
      phoneNumbers: ['+2233445566'],
      addresses: ['321 Marketing Blvd, Promotown, USA'],
      impp: ['sip:jocelyne.shroud@example.com'],
      geo: '41.8781,-87.6298',
      birthday: '1988-07-12',
      anniversary: '2016-11-22',
      sound: 'https://example.com/jocelyne-sound.mp3',
      uid: '44444',
      key: 'public-key-4',
      created_at: '2024-01-01T00:00:00.000Z',
      updated_at: '2024-01-01T00:00:00.000Z',
    },
    {
      id: '5',
      version: '4.0',
      firstName: 'Joshua',
      lastName: 'Brinston',
      middleName: 'E.',
      prefix: 'Mr.',
      suffix: '',
      nickname: 'Josh',
      title: 'Sales Manager',
      organization: 'Sales Corp',
      department: 'Sales',
      jobTitle: 'Sales Manager',
      note: 'Sales professional',
      categories: ['sales', 'manager'],
      urls: ['https://joshuabrinston.sales'],
      photos: ['https://example.com/joshua.jpg'],
      emails: ['joshua.brinston@example.com'],
      phoneNumbers: ['+3344556677'],
      addresses: ['555 Sales Street, Businesstown, USA'],
      impp: ['sip:joshua.brinston@example.com'],
      geo: '29.7604,-95.3698',
      birthday: '1991-11-05',
      anniversary: '2019-04-15',
      sound: 'https://example.com/joshua-sound.mp3',
      uid: '55555',
      key: 'public-key-5',
      created_at: '2024-01-01T00:00:00.000Z',
      updated_at: '2024-01-01T00:00:00.000Z',
    },
  ],
  customers: [],
  contacts: [],
}
