// @ts-nocheck
import type { ImapMessages } from '@/features/mails/mails-types'
import {
  IMIP_CANCEL_ICS,
  IMIP_REPLY_ICS,
  IMIP_REQUEST_ICS,
} from './imip-mail-seed'

function buildInboxPaginationMails(): ImapMessages[] {
  return Array.from({ length: 35 }, (_, i) => {
    const n = 11 + i
    const id = `inbox_${String(n).padStart(3, '0')}`
    const d = new Date(Date.UTC(2025, 10, 28))
    d.setUTCDate(d.getUTCDate() - i)
    return {
      id,
      uid: id,
      attachments: { count: 0, parts: [] },
      contentUri: '',
      seen: true,
      answered: false,
      recent: false,
      deleted: false,
      hasAttachment: i % 9 === 0,
      important: false,
      date: d.toISOString(),
      subject: `Rapport automatique SOGo — cycle ${n}`,
      isMailingList: false,
      from: 'Reporting SOGo <reports@sogo.org>',
      to: ['John Paul <sogo-tests1@example.org>'],
      cc: [] as string[],
      bcc: [] as string[],
      size: 1800 + i * 75,
      imageBlocked: false,
      flags: ['\\Seen'],
      body: `<p>Message généré pour les tests de <strong>pagination</strong> (<code>${id}</code>).</p><p>Corps minimal démo fakeApi.</p>`,
    } as ImapMessages
  })
}

/** Données démo : IDs identiques à `mailbox-messages-seed.ts` (liste ↔ détail). */
export const mailDetailByFolderSeed = {
  INBOX: [
    {
      id: 'inbox_001',
      uid: 'inbox_001',
      attachments: { count: 0, parts: [] },
      contentUri: '',
      seen: false,
      answered: false,
      recent: false,
      deleted: false,
      hasAttachment: false,
      important: false,
      date: '2026-04-20T09:15:00Z',
      subject: 'Entretien candidat — poste développeur',
      isMailingList: false,
      from: 'David Gueto <dgueto@gmail.com>',
      to: ['John Paul <sogo-tests1@example.org>'],
      cc: [] as string[],
      bcc: [] as string[],
      size: 8420,
      imageBlocked: false,
      flags: [] as string[],
      body: '<p>Bonjour,</p><p>Le créneau que vous proposez pour l’entretien (mardi 10 h) me convient parfaitement.</p><p>Cordialement,<br/>David Gueto</p>',
    },
    {
      id: 'inbox_002',
      uid: 'inbox_002',
      attachments: [
        {
          filename: 'facture-INV-2026-042.pdf',
          contentType: 'application/pdf',
          size: 84200,
          downloadUri:
            '/fakeApi/mailboxes/0/folders/INBOX/mails/inbox_002/attachments/0',
          displayUri: '',
          extension: 'pdf',
        },
      ],
      contentUri: '',
      seen: false,
      answered: false,
      recent: false,
      deleted: false,
      hasAttachment: true,
      important: false,
      date: '2026-04-18T14:22:00Z',
      subject: 'Confirmation de paiement — facture INV-2026-042',
      isMailingList: false,
      from: 'James Wilson <james.wilson@yahoo.com>',
      to: ['John Paul <sogo-tests1@example.org>'],
      cc: [] as string[],
      bcc: [] as string[],
      size: 12400,
      imageBlocked: false,
      flags: ['\\Flagged'],
      body: '<p>Cher John,</p><p>Nous accusons réception de votre virement concernant la facture <strong>INV-2026-042</strong>.</p><p>La quittance est jointe à ce message.</p><p>Bien cordialement,<br/>James Wilson — Service comptabilité</p>',
    },
    {
      id: 'inbox_003',
      uid: 'inbox_003',
      attachments: { count: 0, parts: [] },
      contentUri: '',
      seen: true,
      answered: false,
      recent: false,
      deleted: false,
      hasAttachment: false,
      important: false,
      date: '2026-04-15T08:00:00Z',
      subject: 'Revue opérations mensuelle — ordre du jour',
      isMailingList: false,
      from: 'Georges Henry <g.henry@partner.io>',
      to: ['John Paul <sogo-tests1@example.org>'],
      cc: ['Equipe Ops <ops@partner.io>'],
      bcc: [] as string[],
      size: 5100,
      imageBlocked: false,
      flags: ['\\Seen'],
      body: '<p>Bonjour à tous,</p><p>Merci de préparer vos indicateurs pour la revue du <strong>jeudi 17 avril</strong>.</p><p>Georges</p>',
    },
    {
      id: 'inbox_004',
      uid: 'inbox_004',
      attachments: { count: 0, parts: [] },
      contentUri: '',
      seen: true,
      answered: false,
      recent: false,
      deleted: false,
      hasAttachment: false,
      important: false,
      date: '2026-04-10T16:45:00Z',
      subject: 'Demande d’information — offre logicielle',
      isMailingList: false,
      from: 'Thomas Newcastle <t.nc@gmail.com>',
      to: ['John Paul <sogo-tests1@example.org>'],
      cc: [] as string[],
      bcc: [] as string[],
      size: 9800,
      imageBlocked: false,
      flags: ['\\Seen'],
      body: '<p>Bonjour John,</p><p>Pourriez-vous nous transmettre une plaquette tarifaire et un descriptif des modules clés ?</p><p>Merci d’avance,<br/>Thomas</p>',
    },
    {
      id: 'inbox_005',
      uid: 'inbox_005',
      attachments: { count: 0, parts: [] },
      contentUri: '',
      seen: false,
      answered: false,
      recent: false,
      deleted: false,
      hasAttachment: false,
      important: false,
      date: '2026-04-08T11:30:00Z',
      subject: 'Préparation FOSDEM — point d’équipe',
      isMailingList: false,
      from: 'Jane Smith <jane.smith@sogo.nu>',
      to: ['John Paul <sogo-tests1@example.org>'],
      cc: [] as string[],
      bcc: [] as string[],
      size: 3200,
      imageBlocked: false,
      flags: [] as string[],
      body: '<p>Hi John,</p><p>Peux-tu bloquer deux créneaux cette semaine pour finaliser les slides FOSDEM ?</p><p>Merci,<br/>Jane</p>',
    },
    {
      id: 'inbox_006',
      uid: 'inbox_006',
      attachments: { count: 0, parts: [] },
      contentUri: '',
      seen: true,
      answered: false,
      recent: false,
      deleted: false,
      hasAttachment: false,
      important: false,
      date: '2026-04-05T13:00:00Z',
      subject: 'Onboarding client — appel de lancement',
      isMailingList: false,
      from: 'Jessica Longisland <j.longisland@gmail.com>',
      to: ['John Paul <sogo-tests1@example.org>'],
      cc: [] as string[],
      bcc: [] as string[],
      size: 6700,
      imageBlocked: false,
      flags: ['\\Seen'],
      body: '<p>Bonjour John,</p><p>Ravi de démarrer le projet avec vous. Le lien de visio : <code>https://meet.example.com/onboarding-atlas</code></p><p>Jessica</p>',
    },
    {
      id: 'inbox_007',
      uid: 'inbox_007',
      attachments: { count: 0, parts: [] },
      contentUri: '',
      seen: false,
      answered: false,
      recent: false,
      deleted: false,
      hasAttachment: false,
      important: false,
      date: '2026-04-02T10:10:00Z',
      subject: 'Invitation démo produit',
      isMailingList: false,
      from: 'Claire Martin <c.martin@sogomail.eu>',
      to: ['John Paul <sogo-tests1@example.org>'],
      cc: [] as string[],
      bcc: [] as string[],
      size: 4500,
      imageBlocked: false,
      flags: [] as string[],
      body: '<p>Bonjour John,</p><p>Seriez-vous disponible <strong>mardi après-midi</strong> pour une démo de 45 minutes ?</p><p>Claire</p>',
    },
    {
      id: 'inbox_imip_request',
      uid: 'inbox_imip_request',
      attachments: { count: 0, parts: [] },
      contentUri: '',
      seen: false,
      answered: false,
      recent: false,
      deleted: false,
      hasAttachment: false,
      important: false,
      date: '2026-07-14T08:00:00Z',
      subject: 'Invitation: Product demo (iMIP)',
      isMailingList: false,
      from: 'Claire Martin <c.martin@sogomail.eu>',
      to: ['John Paul <sogo-tests1@example.org>'],
      cc: [] as string[],
      bcc: [] as string[],
      size: 3200,
      imageBlocked: false,
      flags: [] as string[],
      mail_type: ['event'],
      mail_type_data: [{ ics_content: IMIP_REQUEST_ICS }],
    },
    {
      id: 'inbox_imip_cancel',
      uid: 'inbox_imip_cancel',
      attachments: { count: 0, parts: [] },
      contentUri: '',
      seen: false,
      answered: false,
      recent: false,
      deleted: false,
      hasAttachment: false,
      important: false,
      date: '2026-07-14T09:00:00Z',
      subject: 'Cancelled: Product demo (iMIP)',
      isMailingList: false,
      from: 'Claire Martin <c.martin@sogomail.eu>',
      to: ['John Paul <sogo-tests1@example.org>'],
      cc: [] as string[],
      bcc: [] as string[],
      size: 2800,
      imageBlocked: false,
      flags: [] as string[],
      mail_type: ['event'],
      mail_type_data: [{ ics_content: IMIP_CANCEL_ICS }],
    },
    {
      id: 'inbox_imip_reply',
      uid: 'inbox_imip_reply',
      attachments: { count: 0, parts: [] },
      contentUri: '',
      seen: false,
      answered: false,
      recent: false,
      deleted: false,
      hasAttachment: false,
      important: false,
      date: '2026-07-14T10:00:00Z',
      subject: 'Re: Product demo (iMIP)',
      isMailingList: false,
      from: 'John Paul <sogo-tests1@example.org>',
      to: ['Claire Martin <c.martin@sogomail.eu>'],
      cc: [] as string[],
      bcc: [] as string[],
      size: 2600,
      imageBlocked: false,
      flags: [] as string[],
      mail_type: ['event'],
      mail_type_data: [{ ics_content: IMIP_REPLY_ICS }],
    },
    {
      id: 'inbox_008',
      uid: 'inbox_008',
      attachments: { count: 0, parts: [] },
      contentUri: '',
      seen: true,
      answered: false,
      recent: false,
      deleted: false,
      hasAttachment: false,
      important: false,
      date: '2026-03-28T17:20:00Z',
      subject: 'Suivi de notre échange',
      isMailingList: false,
      from: 'Claire Martin <c.martin@sogomail.eu>',
      to: ['John Paul <sogo-tests1@example.org>'],
      cc: [] as string[],
      bcc: [] as string[],
      size: 2900,
      imageBlocked: false,
      flags: ['\\Seen'],
      body: '<p>Bonjour John,</p><p>Merci encore pour notre échange d’hier. Comme convenu, je vous envoie le récapitulatif en pièce jointe interne.</p><p>Claire</p>',
    },
    {
      id: 'inbox_009',
      uid: 'inbox_009',
      attachments: { count: 0, parts: [] },
      contentUri: '',
      seen: false,
      answered: false,
      recent: false,
      deleted: false,
      hasAttachment: true,
      important: false,
      date: '2026-03-22T09:00:00Z',
      subject: 'Webinaire « collaboration hybride »',
      isMailingList: true,
      from: 'Azra Anderson <azra.anderson@gmail.com>',
      to: ['John Paul <sogo-tests1@example.org>'],
      cc: [] as string[],
      bcc: [] as string[],
      size: 15600,
      imageBlocked: false,
      flags: [] as string[],
      body: '<p>Bonjour,</p><p>Inscription ouverte pour le webinaire du <strong>30 avril</strong>. Programme : 45 minutes de présentation puis Q&amp;A.</p><p>Azra</p>',
    },
    {
      id: 'inbox_010',
      uid: 'inbox_010',
      attachments: [
        {
          filename: 'CV-Diana-Presley.pdf',
          contentType: 'application/pdf',
          size: 220000,
          downloadUri:
            '/fakeApi/mailboxes/0/folders/INBOX/mails/inbox_010/attachments/0',
          displayUri: '',
          extension: 'pdf',
        },
      ],
      contentUri: '',
      seen: true,
      answered: false,
      recent: false,
      deleted: false,
      hasAttachment: true,
      important: false,
      date: '2026-03-15T12:00:00Z',
      subject: 'Candidature spontanée',
      isMailingList: false,
      from: 'Diana Presley <diana.presley9@gmail.com>',
      to: ['John Paul <sogo-tests1@example.org>'],
      cc: [] as string[],
      bcc: [] as string[],
      size: 22000,
      imageBlocked: false,
      flags: ['\\Seen'],
      body: '<p>Madame, Monsieur,</p><p>Veuillez trouver ci-joint mon CV pour une candidature spontanée au poste de chef de projet.</p><p>Cordialement,<br/>Diana Presley</p>',
    },
    ...buildInboxPaginationMails(),
  ],
  Sent: [
    {
      id: 'sent_001',
      uid: 'sent_001',
      attachments: [
        {
          filename: 'proposition-signee.pdf',
          contentType: 'application/pdf',
          size: 120000,
          downloadUri:
            '/fakeApi/mailboxes/0/folders/Sent/mails/sent_001/attachments/0',
          displayUri: '',
          extension: 'pdf',
        },
      ],
      contentUri: '',
      seen: true,
      answered: true,
      recent: false,
      deleted: false,
      hasAttachment: true,
      important: false,
      date: '2026-04-19T15:40:00Z',
      subject: 'Re: Proposition commerciale — version finale',
      isMailingList: false,
      from: { name: 'John Paul', email: 'sogo-tests1@example.org' },
      to: ['Claire Martin <c.martin@sogomail.eu>'],
      cc: [] as string[],
      bcc: [] as string[],
      size: 18800,
      imageBlocked: false,
      flags: ['\\Seen'],
      body: '<p>Bonjour Claire,</p><p>Comme convenu, vous trouverez la version finale signée en pièce jointe.</p><p>Bien cordialement,<br/>John Paul</p>',
    },
    {
      id: 'sent_002',
      uid: 'sent_002',
      attachments: { count: 0, parts: [] },
      contentUri: '',
      seen: true,
      answered: true,
      recent: false,
      deleted: false,
      hasAttachment: false,
      important: false,
      date: '2026-04-17T08:55:00Z',
      subject: 'Compte-rendu réunion équipe',
      isMailingList: false,
      from: { name: 'John Paul', email: 'sogo-tests1@example.org' },
      to: [
        'Jane Smith <jane.smith@sogo.nu>',
        'Georges Henry <g.henry@partner.io>',
      ],
      cc: [] as string[],
      bcc: [] as string[],
      size: 4100,
      imageBlocked: false,
      flags: ['\\Seen', '\\Answered'],
      body: '<p>Bonjour à toutes et tous,</p><p><strong>Actions :</strong></p><ul><li>Jane — maquettes v2 pour vendredi</li><li>Georges — chiffrage module SSO</li></ul><p>John</p>',
    },
    {
      id: 'sent_003',
      uid: 'sent_003',
      attachments: { count: 0, parts: [] },
      contentUri: '',
      seen: true,
      answered: false,
      recent: false,
      deleted: false,
      hasAttachment: false,
      important: false,
      date: '2026-04-12T18:05:00Z',
      subject: 'Accusé de réception — demande support',
      isMailingList: false,
      from: { name: 'John Paul', email: 'sogo-tests1@example.org' },
      to: ['Support SOGo <support@sogo.org>'],
      cc: [] as string[],
      bcc: [] as string[],
      size: 1200,
      imageBlocked: false,
      flags: ['\\Seen'],
      body: '<p>Bonjour,</p><p>Votre ticket <strong>#45821</strong> a bien été enregistré. Nous vous répondrons sous 24 h ouvrées.</p><p>John Paul</p>',
    },
  ],
  Drafts: [
    {
      id: 'drafts_001',
      uid: 'drafts_001',
      attachments: { count: 0, parts: [] },
      contentUri: '',
      seen: false,
      answered: false,
      recent: false,
      deleted: false,
      hasAttachment: false,
      important: false,
      date: '2026-04-21T07:30:00Z',
      subject: 'Brouillon — proposition projet Atlas',
      isMailingList: false,
      from: { name: 'John Paul', email: 'sogo-tests1@example.org' },
      to: [] as string[],
      cc: [] as string[],
      bcc: [] as string[],
      size: 800,
      imageBlocked: false,
      flags: [] as string[],
      body: '<p>Bonjour,</p><p>Nous sommes ravis de vous présenter notre offre pour le projet <em>Atlas</em>…</p><p><em>[brouillon non terminé]</em></p>',
    },
    {
      id: 'drafts_002',
      uid: 'drafts_002',
      attachments: { count: 0, parts: [] },
      contentUri: '',
      seen: false,
      answered: false,
      recent: false,
      deleted: false,
      hasAttachment: false,
      important: false,
      date: '2026-04-20T22:00:00Z',
      subject: '(sans objet)',
      isMailingList: false,
      from: { name: 'John Paul', email: 'sogo-tests1@example.org' },
      to: [] as string[],
      cc: [] as string[],
      bcc: [] as string[],
      size: 400,
      imageBlocked: false,
      flags: [] as string[],
      body: '',
    },
  ],
  Trash: [
    {
      id: 'trash_001',
      uid: 'trash_001',
      attachments: { count: 0, parts: [] },
      contentUri: '',
      seen: true,
      answered: false,
      recent: false,
      deleted: true,
      hasAttachment: false,
      important: false,
      date: '2025-11-03T10:00:00Z',
      subject: 'Ancienne newsletter — archives 2024',
      isMailingList: true,
      from: 'Newsletter <news@example.com>',
      to: ['John Paul <sogo-tests1@example.org>'],
      cc: [] as string[],
      bcc: [] as string[],
      size: 2100,
      imageBlocked: false,
      flags: ['\\Seen', '\\Deleted'],
      body: '<p>Les temps forts du T3 2024 : nouveautés produit, témoignages clients…</p>',
    },
    {
      id: 'trash_002',
      uid: 'trash_002',
      attachments: { count: 0, parts: [] },
      contentUri: '',
      seen: true,
      answered: false,
      recent: false,
      deleted: true,
      hasAttachment: false,
      important: false,
      date: '2025-09-14T09:30:00Z',
      subject: 'Invitation expirée — événement annulé',
      isMailingList: false,
      from: 'Events <events@example.com>',
      to: ['John Paul <sogo-tests1@example.org>'],
      cc: [] as string[],
      bcc: [] as string[],
      size: 1500,
      imageBlocked: false,
      flags: ['\\Seen', '\\Deleted'],
      body: '<p>L’événement du 20 septembre est <strong>annulé</strong>. Les inscriptions sont closes.</p>',
    },
  ],
  Junk: [
    {
      id: 'junk_001',
      uid: 'junk_001',
      attachments: { count: 0, parts: [] },
      contentUri: '',
      seen: false,
      answered: false,
      recent: false,
      deleted: false,
      hasAttachment: false,
      important: false,
      date: '2026-04-21T03:12:00Z',
      subject: 'URGENT : vous avez gagné un iPhone (offre limitée)',
      isMailingList: false,
      from: 'Promo Winner <winner@spam-example.net>',
      to: ['John Paul <sogo-tests1@example.org>'],
      cc: [] as string[],
      bcc: [] as string[],
      size: 900,
      imageBlocked: false,
      flags: ['\\Junk'],
      body: '<p><strong>AGISSEZ MAINTENANT</strong> — cliquez sur le lien douteux ci-dessous…</p><p><em>(message typique de courrier indésirable)</em></p>',
    },
  ],
  'Projects/2024/Frontend': [
    {
      id: 'proj_fe_001',
      uid: 'proj_fe_001',
      attachments: { count: 0, parts: [] },
      contentUri: '',
      seen: false,
      answered: false,
      recent: false,
      deleted: false,
      hasAttachment: false,
      important: false,
      date: '2026-04-01T09:00:00Z',
      subject: 'Frontend — standup quotidien',
      isMailingList: false,
      from: 'Lead Dev <lead@example.com>',
      to: ['Frontend Team <frontend@example.com>'],
      cc: [] as string[],
      bcc: [] as string[],
      size: 2600,
      imageBlocked: false,
      flags: [] as string[],
      body: '<p>Rappel : daily à <strong>10 h</strong> (fuseau Europe/Paris).</p>',
    },
    {
      id: 'proj_fe_002',
      uid: 'proj_fe_002',
      attachments: { count: 0, parts: [] },
      contentUri: '',
      seen: true,
      answered: false,
      recent: false,
      deleted: false,
      hasAttachment: false,
      important: false,
      date: '2026-03-29T14:00:00Z',
      subject: 'Revue de composants UI',
      isMailingList: false,
      from: 'Reviewer <reviewer@example.com>',
      to: ['Frontend Team <frontend@example.com>'],
      cc: [] as string[],
      bcc: [] as string[],
      size: 3300,
      imageBlocked: false,
      flags: ['\\Seen'],
      body: '<p>Merci de relire la PR sur le bouton primaire (branche <code>feat/ui-primary</code>).</p>',
    },
    {
      id: 'proj_fe_003',
      uid: 'proj_fe_003',
      attachments: [
        {
          filename: 'screenshot-login.png',
          contentType: 'image/png',
          size: 240000,
          downloadUri:
            '/fakeApi/mailboxes/0/folders/Projects%2F2024%2FFrontend/mails/proj_fe_003/attachments/0',
          displayUri: '',
          extension: 'png',
        },
      ],
      contentUri: '',
      seen: false,
      answered: false,
      recent: false,
      deleted: false,
      hasAttachment: true,
      important: false,
      date: '2026-03-27T11:20:00Z',
      subject: 'Anomalie — formulaire de login',
      isMailingList: false,
      from: 'QA <qa@example.com>',
      to: ['Frontend Team <frontend@example.com>'],
      cc: ['John Paul <sogo-tests1@example.org>'],
      bcc: [] as string[],
      size: 7200,
      imageBlocked: false,
      flags: [] as string[],
      body: '<p>Bug reproduit sur Firefox 137 : la validation du mot de passe ne s’affiche pas (capture jointe).</p>',
    },
  ],
  'Projects/2024/Frontend/React': [
    {
      id: 'proj_r_001',
      uid: 'proj_r_001',
      attachments: { count: 0, parts: [] },
      contentUri: '',
      seen: true,
      answered: false,
      recent: false,
      deleted: false,
      hasAttachment: false,
      important: false,
      date: '2026-03-25T16:00:00Z',
      subject: 'React — migration vers React 19',
      isMailingList: false,
      from: 'Tech Lead <techlead@example.com>',
      to: ['John Paul <sogo-tests1@example.org>'],
      cc: [] as string[],
      bcc: [] as string[],
      size: 5400,
      imageBlocked: false,
      flags: ['\\Seen'],
      body: '<p>Le plan de migration est publié sur le wiki interne. Merci de valider la section « breaking changes ».</p>',
    },
    {
      id: 'proj_r_002',
      uid: 'proj_r_002',
      attachments: [
        {
          filename: 'webpack-report.html',
          contentType: 'text/html',
          size: 450000,
          downloadUri:
            '/fakeApi/mailboxes/0/folders/Projects%2F2024%2FFrontend%2FReact/mails/proj_r_002/attachments/0',
          displayUri: '',
          extension: 'html',
        },
      ],
      contentUri: '',
      seen: false,
      answered: false,
      recent: false,
      deleted: false,
      hasAttachment: true,
      important: false,
      date: '2026-03-24T10:45:00Z',
      subject: 'Bundle size — rapport hebdo',
      isMailingList: false,
      from: 'Perf <perf@example.com>',
      to: ['John Paul <sogo-tests1@example.org>'],
      cc: [] as string[],
      bcc: [] as string[],
      size: 8900,
      imageBlocked: false,
      flags: [] as string[],
      body: '<p>Analyse webpack jointe : principales dépendances à surveiller listées page 1 du rapport.</p>',
    },
    {
      id: 'proj_r_003',
      uid: 'proj_r_003',
      attachments: { count: 0, parts: [] },
      contentUri: '',
      seen: true,
      answered: false,
      recent: false,
      deleted: false,
      hasAttachment: false,
      important: false,
      date: '2026-03-20T13:30:00Z',
      subject: 'Accessibilité — audit rapide',
      isMailingList: false,
      from: 'A11y <a11y@example.com>',
      to: ['John Paul <sogo-tests1@example.org>'],
      cc: [] as string[],
      bcc: [] as string[],
      size: 3100,
      imageBlocked: false,
      flags: ['\\Seen'],
      body: '<p>Les correctifs prioritaires (contraste, focus visible) sont détaillés dans le tableau page 2 du document partagé.</p>',
    },
  ],
} as unknown as Record<string, ImapMessages[]>
