import deepmerge from 'deepmerge'
import { getRequestConfig } from 'next-intl/server'
import { routing } from './config'

/**
 * Static message bundles compiled at build time by ``scripts/compile-messages.mjs``.
 *
 * Each locale's file is a single JSON object deep-merged from all individual
 * ``src/messages/<locale>/*.json`` files, so no runtime ``fs`` or dynamic
 * ``import()`` is needed.  This is required for Next.js standalone output to
 * work correctly.
 *
 * When the compiled files are absent (e.g. in dev mode without the prebuild
 * step), a dynamic fallback is used.  In production, the build pipeline always
 * runs ``compile-messages.mjs`` before ``next build``, so the imports resolve.
 */

// ── Static pre-compiled imports ───────────────────────────────────────────

// These are resolved at build time by webpack/esbuild.
// The actual files are generated by scripts/compile-messages.mjs.
// We use try/require because the files may not exist in dev.
let enMessages: Record<string, unknown> = {}
let deMessages: Record<string, unknown> = {}
let frMessages: Record<string, unknown> = {}
let esMessages: Record<string, unknown> = {}
let zhMessages: Record<string, unknown> = {}
let itMessages: Record<string, unknown> = {}
let ptMessages: Record<string, unknown> = {}
let nlMessages: Record<string, unknown> = {}
let plMessages: Record<string, unknown> = {}
let ruMessages: Record<string, unknown> = {}
let svMessages: Record<string, unknown> = {}
let daMessages: Record<string, unknown> = {}
let fiMessages: Record<string, unknown> = {}
let noMessages: Record<string, unknown> = {}
let csMessages: Record<string, unknown> = {}
let elMessages: Record<string, unknown> = {}
let trMessages: Record<string, unknown> = {}
let huMessages: Record<string, unknown> = {}
let roMessages: Record<string, unknown> = {}
let jaMessages: Record<string, unknown> = {}
let hiMessages: Record<string, unknown> = {}
let arMessages: Record<string, unknown> = {}
let koMessages: Record<string, unknown> = {}
let thMessages: Record<string, unknown> = {}
let viMessages: Record<string, unknown> = {}
let idMessages: Record<string, unknown> = {}

try {
  enMessages = require('./compiled-messages/en.json')
} catch {
  // Fallback handled below
}
try {
  deMessages = require('./compiled-messages/de.json')
} catch {
  /* empty */
}
try {
  frMessages = require('./compiled-messages/fr.json')
} catch {
  /* empty */
}
try {
  esMessages = require('./compiled-messages/es.json')
} catch {
  /* empty */
}
try {
  zhMessages = require('./compiled-messages/zh.json')
} catch {
  /* empty */
}
try {
  itMessages = require('./compiled-messages/it.json')
} catch {
  /* empty */
}
try {
  ptMessages = require('./compiled-messages/pt.json')
} catch {
  /* empty */
}
try {
  nlMessages = require('./compiled-messages/nl.json')
} catch {
  /* empty */
}
try {
  plMessages = require('./compiled-messages/pl.json')
} catch {
  /* empty */
}
try {
  ruMessages = require('./compiled-messages/ru.json')
} catch {
  /* empty */
}
try {
  svMessages = require('./compiled-messages/sv.json')
} catch {
  /* empty */
}
try {
  daMessages = require('./compiled-messages/da.json')
} catch {
  /* empty */
}
try {
  fiMessages = require('./compiled-messages/fi.json')
} catch {
  /* empty */
}
try {
  noMessages = require('./compiled-messages/no.json')
} catch {
  /* empty */
}
try {
  csMessages = require('./compiled-messages/cs.json')
} catch {
  /* empty */
}
try {
  elMessages = require('./compiled-messages/el.json')
} catch {
  /* empty */
}
try {
  trMessages = require('./compiled-messages/tr.json')
} catch {
  /* empty */
}
try {
  huMessages = require('./compiled-messages/hu.json')
} catch {
  /* empty */
}
try {
  roMessages = require('./compiled-messages/ro.json')
} catch {
  /* empty */
}
try {
  jaMessages = require('./compiled-messages/ja.json')
} catch {
  /* empty */
}
try {
  hiMessages = require('./compiled-messages/hi.json')
} catch {
  /* empty */
}
try {
  arMessages = require('./compiled-messages/ar.json')
} catch {
  /* empty */
}
try {
  koMessages = require('./compiled-messages/ko.json')
} catch {
  /* empty */
}
try {
  thMessages = require('./compiled-messages/th.json')
} catch {
  /* empty */
}
try {
  viMessages = require('./compiled-messages/vi.json')
} catch {
  /* empty */
}
try {
  idMessages = require('./compiled-messages/id.json')
} catch {
  /* empty */
}

// ── Pre-built locale map ──────────────────────────────────────────────────

const PRECOMPILED: Record<string, Record<string, unknown>> = {
  en: enMessages,
  de: deMessages,
  fr: frMessages,
  es: esMessages,
  zh: zhMessages,
  it: itMessages,
  pt: ptMessages,
  nl: nlMessages,
  pl: plMessages,
  ru: ruMessages,
  sv: svMessages,
  da: daMessages,
  fi: fiMessages,
  no: noMessages,
  cs: csMessages,
  el: elMessages,
  tr: trMessages,
  hu: huMessages,
  ro: roMessages,
  ja: jaMessages,
  hi: hiMessages,
  ar: arMessages,
  ko: koMessages,
  th: thMessages,
  vi: viMessages,
  id: idMessages,
}

// ── Dynamic fallback (dev only) ───────────────────────────────────────────

async function loadDynamic(locale: string): Promise<Record<string, unknown>> {
  // Only used when pre-compiled files are missing (e.g. first dev run)
  // This mirrors the original filesystem-based approach.
  const fs = await import('fs')
  const path = await import('path')

  const localeDir = `src/messages/${locale}`
  if (!fs.existsSync(localeDir)) return {}

  const messages: Record<string, unknown> = {}

  function getAllFiles(dirPath: string): string[] {
    const entries = fs.readdirSync(dirPath, { withFileTypes: true })
    const files: string[] = []
    for (const entry of entries) {
      const fullPath = path.join(dirPath, entry.name)
      if (entry.isDirectory()) {
        files.push(...getAllFiles(fullPath))
      } else {
        files.push(fullPath)
      }
    }
    return files
  }

  const allFiles = getAllFiles(localeDir)
  for (const file of allFiles) {
    if (!file.endsWith('.json')) continue
    const content = JSON.parse(fs.readFileSync(file, 'utf-8'))
    Object.assign(messages, content)
  }

  return messages
}

// ── Request config ────────────────────────────────────────────────────────

export default getRequestConfig(async ({ requestLocale }) => {
  let locale = await requestLocale
  if (!locale || !routing.locales.includes(locale as string)) {
    locale = routing.defaultLocale
  }

  // Try pre-compiled first, fall back to dynamic (dev-only)
  let defaultMessages = PRECOMPILED[routing.defaultLocale]
  if (!defaultMessages || Object.keys(defaultMessages).length === 0) {
    defaultMessages = await loadDynamic(routing.defaultLocale)
  }

  let messages: Record<string, unknown> = {}
  if (locale !== routing.defaultLocale) {
    messages = PRECOMPILED[locale as string] || (await loadDynamic(locale as string))
  }

  return {
    locale,
    messages: deepmerge(defaultMessages, messages),
  }
})
