import deepmerge from 'deepmerge'
import { getRequestConfig } from 'next-intl/server'
import { routing } from './config'

/**
 * Static message bundles compiled at build time by ``scripts/compile-messages.mjs``.
 *
 * Each locale's file is a single JSON object deep-merged from all individual
 * ``src/messages/<locale>/*.json`` files, so no runtime ``fs`` or dynamic
 * ``import()`` is needed.  This is required for Next.js standalone output to
 * work correctly.
 *
 * When the compiled files are absent (e.g. in dev mode without the prebuild
 * step), a dynamic fallback is used.  In production, the build pipeline always
 * runs ``compile-messages.mjs`` before ``next build``, so the imports resolve.
 */

// ── Static pre-compiled imports ───────────────────────────────────────────

// These are resolved at build time by webpack/esbuild.
// The actual files are generated by scripts/compile-messages.mjs.
// We use try/require because the files may not exist in dev.
let enMessages: Record<string, unknown> = {}
let deMessages: Record<string, unknown> = {}
let frMessages: Record<string, unknown> = {}
let esMessages: Record<string, unknown> = {}
let zhMessages: Record<string, unknown> = {}

try {
  enMessages = require('./compiled-messages/en.json')
} catch {
  // Fallback handled below
}
try {
  deMessages = require('./compiled-messages/de.json')
} catch {
  /* empty */
}
try {
  frMessages = require('./compiled-messages/fr.json')
} catch {
  /* empty */
}
try {
  esMessages = require('./compiled-messages/es.json')
} catch {
  /* empty */
}
try {
  zhMessages = require('./compiled-messages/zh.json')
} catch {
  /* empty */
}

// ── Pre-built locale map ──────────────────────────────────────────────────

const PRECOMPILED: Record<string, Record<string, unknown>> = {
  en: enMessages,
  de: deMessages,
  fr: frMessages,
  es: esMessages,
  zh: zhMessages,
}

// ── Dynamic fallback (dev only) ───────────────────────────────────────────

async function loadDynamic(locale: string): Promise<Record<string, unknown>> {
  // Only used when pre-compiled files are missing (e.g. first dev run)
  // This mirrors the original filesystem-based approach.
  const fs = await import('fs')
  const path = await import('path')

  const localeDir = `src/messages/${locale}`
  if (!fs.existsSync(localeDir)) return {}

  const messages: Record<string, unknown> = {}

  function getAllFiles(dirPath: string): string[] {
    const entries = fs.readdirSync(dirPath, { withFileTypes: true })
    const files: string[] = []
    for (const entry of entries) {
      const fullPath = path.join(dirPath, entry.name)
      if (entry.isDirectory()) {
        files.push(...getAllFiles(fullPath))
      } else {
        files.push(fullPath)
      }
    }
    return files
  }

  const allFiles = getAllFiles(localeDir)
  for (const file of allFiles) {
    if (!file.endsWith('.json')) continue
    const content = JSON.parse(fs.readFileSync(file, 'utf-8'))
    Object.assign(messages, content)
  }

  return messages
}

// ── Request config ────────────────────────────────────────────────────────

export default getRequestConfig(async ({ requestLocale }) => {
  let locale = await requestLocale
  if (!locale || !routing.locales.includes(locale as string)) {
    locale = routing.defaultLocale
  }

  // Try pre-compiled first, fall back to dynamic (dev-only)
  let defaultMessages = PRECOMPILED[routing.defaultLocale]
  if (!defaultMessages || Object.keys(defaultMessages).length === 0) {
    defaultMessages = await loadDynamic(routing.defaultLocale)
  }

  let messages: Record<string, unknown> = {}
  if (locale !== routing.defaultLocale) {
    messages = PRECOMPILED[locale as string] || (await loadDynamic(locale as string))
  }

  return {
    locale,
    messages: deepmerge(defaultMessages, messages),
  }
})
